// breadcrumb_models.dart
import 'dart:ui';

import 'package:auto_route/auto_route.dart';

class BreadcrumbItem {
  final String name;
  final String routePath;
  final bool isClickable;
  final VoidCallback? customNavigationCallback;
  final RouteData? routeInfo;

  const BreadcrumbItem({
    required this.name,
    required this.routePath,
    this.isClickable = true,
    this.customNavigationCallback,
    this.routeInfo,
  });

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BreadcrumbItem &&
          runtimeType == other.runtimeType &&
          routePath == other.routePath;

  @override
  int get hashCode => routePath.hashCode;
}

class BreadcrumbConfig {
  final List<BreadcrumbItem> customBreadcrumbs;
  final bool useAutoGenerated;

  const BreadcrumbConfig({
    this.customBreadcrumbs = const [],
    this.useAutoGenerated = true,
  });
}
